src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = ["ROLE_USER"];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=520)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=510)
     */
    private $display_name;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Skill", inversedBy="users")
     */
    private $skills;

    /**
     * @ORM\OneToMany(targetEntity="PlanningEntry", mappedBy="user", orphanRemoval=true)
     */
    private $planning_entries;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cellphone = "";

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone = "";

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $address = "";

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nivol = "";

    public function __construct()
    {
        $this->skills = new ArrayCollection();
        $this->planning_entries = new ArrayCollection();
        $this->birthday = new DateTime();
        $d = new DateTime();
        $d->setTimestamp(time());
        $this->setBirthday($d);
        $this->nivol = "";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function isAdmin(): bool
    {
        return in_array("ROLE_ADMIN", $this->roles);
    }

    public function isHyperAdmin(): bool
    {
        return in_array("ROLE_HYPER_ADMIN", $this->roles);
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }


    public function getBirthday(): ?DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    /**
     * @return Collection|Skill[]
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(Skill $skill): self
    {
        if (!$this->skills->contains($skill)) {
            $this->skills[] = $skill;
        }

        return $this;
    }

    public function removeSkill(Skill $skill): self
    {
        if ($this->skills->contains($skill)) {
            $this->skills->removeElement($skill);
        }

        return $this;
    }

    /**
     * @return Collection|PlanningEntry[]
     */
    public function getPlanningEntries(): Collection
    {
        return $this->planning_entries;
    }

    public function addPlanningEntry(PlanningEntry $planning_entry): self
    {
        if (!$this->planning_entries->contains($planning_entry)) {
            $this->planning_entries[] = $planning_entry;
            $planning_entry->setUser($this);
        }

        return $this;
    }

    public function removePlanningEntry(PlanningEntry $planning_entry): self
    {
        if ($this->planning_entries->contains($planning_entry)) {
            $this->planning_entries->removeElement($planning_entry);
            // set the owning side to null (unless already changed)
            if ($planning_entry->getUser() === $this) {
                $planning_entry->setUser(null);
            }
        }

        return $this;
    }

    public function getCellphone(): ?string
    {
        return $this->cellphone;
    }

    public function setCellphone(string $cellphone): self
    {
        $this->cellphone = $cellphone;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getNivol(): ?string
    {
        return $this->nivol;
    }

    public function setNivol(string $nivol): self
    {
        $this->nivol = $nivol;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no">

        <title>{% block title %}CRF-Manager{% endblock %}</title>

        {{ encore_entry_link_tags('app') }}
        {{ encore_entry_script_tags('app') }}
        {% block stylesheets %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}

        {% endblock %}
    </body>
</html>

templates/close.html.twig
<html>
<body>
<script>window.close()</script>
</body>
</html>

templates/navbar.html.twig
{% set knowTopic = topicActive is defined %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">CRF-Manager</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link"
                   href="{{ path('planning') }}">{% trans %}My planning{% endtrans %}{% if knowTopic and topicActive == "planning" %}
                        <span
                                class="sr-only">(current)</span>{% endif %}</a>
            </li>
            {% if app.user is not null and app.user.admin %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% trans %}Admin{% endtrans %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item"
                           href="{{ path('admin_timeline') }}">{% trans %}Timeline{% endtrans %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"
                           href="{{ path('admin_user_view') }}">{% trans %}Manage users{% endtrans %}</a>
                        <a class="dropdown-item"
                           href="{{ path('admin_skill_view') }}">{% trans %}Manage skills{% endtrans %}</a>

                    </div>
                </li>
            {% endif %}
            {% if app.user is not null and app.user.hyperAdmin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('hyper_admin') }}">HyperAdmin</a>
                </li>
            {% endif %}
        </ul>
    </div>

    {% if app.user is not null %}
        <a href="{{ path('user_profil') }}">
            <span class="navbar-text font-weight-bold">{{ app.user.displayName }}</span>
        </a>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ path('app_logout') }}">{% trans %}Disconnect{% endtrans %}</a>
            </li>
        </ul>
    {% else %}
        <a href="{{ path('app_login') }}">
            <span class="navbar-text font-weight-bold">{% trans %}Login{% endtrans %}</span>
        </a>
    {% endif %}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


</nav>